from dataclasses import dataclass


@dataclass(slots=True)
class DomainError(Exception):
    error_code: str
    message: str
    status_code: int = 422


class ErrorCodes:
    OUTSIDE_BUSINESS_HOURS = "OUTSIDE_BUSINESS_HOURS"
    HOLIDAY_NOT_ALLOWED = "HOLIDAY_NOT_ALLOWED"
    INSUFFICIENT_ADVANCE = "INSUFFICIENT_ADVANCE"
    PROFESSIONAL_OVERLAP = "PROFESSIONAL_OVERLAP"
    USER_BOOKING_LIMIT = "USER_BOOKING_LIMIT"
    BOOKING_NOT_FOUND = "BOOKING_NOT_FOUND"
    BOOKING_ALREADY_CANCELLED = "BOOKING_ALREADY_CANCELLED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    SERVICE_NOT_FOUND = "SERVICE_NOT_FOUND"
    INVALID_DATE_RANGE = "INVALID_DATE_RANGE"

